### ISSUE TITLE
Implementing semantics about traps

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#109]
- [x] #108
- [x] #111
- [x] #110
- [x] Run traps after reading commands 8169166439d6145b906720708ef43a989343b683
- [x] #114 #115
    - [x] [Prevent running traps while running another](https://github.com/magicant/yash-rs/pull/114/files#diff-b9aa8606985836413fcbfcef292bb0c68be63f98629261c953f657fbcaba635fR36) cd9af1c6406931a2654805426ce94fb589050049
        - [x] [Allow reentrance if in subshell in trap](https://github.com/magicant/yash-rs/commit/cd9af1c6406931a2654805426ce94fb589050049#diff-b9aa8606985836413fcbfcef292bb0c68be63f98629261c953f657fbcaba635fR207)
    - [x] [Include the signal name](https://github.com/magicant/yash-rs/pull/114/files#diff-1a7b3c4f1baf977d484791bfbe1c1f0d1c4bfd8badac994aadf6c1eae3a986b2R129) for the label of `Source::Trap`
b9aa8606985836413fcbfcef292bb0c68be63f98629261c953f657fbcaba635fR140-R142)
- [x] #116
    - [x] #120 (especially in command substitutions)
- [x] Internal handlers for SIGINT, SIGTERM, SIGQUIT, SIGTTIN, SIGTTOU, and SIGTSTP
- [x] #236
    - [x] #234

More trap-related tasks tracked in #260

**Comment by magicant** [comment]
> Run traps while reading commands

POSIX does not precisely specify when the shell should execute trap commands. Some shells (bash, dash, and mksh) do not seem to run them while waiting for command-line input. If their behavior is acceptable, yash-rs's implementation can be simpler than the current yash.

If yash-rs is going to run traps while reading input, we will need a clever trick to make it possible to read input and run commands simultaneously. Especially:

- Running commands requires a mutable reference to the entire `Env` while the lexer and parser also need a (non-mutable) reference to the alias set.
- The shell must suspend reading when it receives a signal. In other words, the shell must not read input while running traps.
- If line-editing is active, the shell should also suspend it while running traps.
