### ISSUE TITLE
Command-line argument parsing for built-ins (POSIX portability)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#122]
Features for non-portable extensions are tracked in #321.

- [x] Basics #125
    - Short options
    - Long options
    - Argument-taking options
    - Separator (`--`)
- [x] Syntax error message 14b1475f11c5e539f2273800e809cee9429edf9e
    - Wrong option
    - Ambiguous long option
    - Missing option argument
    - Unexpected long option argument
- [x] Mode: enabling/disabling long options #127
- [x] Show the built-in name in error messages
- [x] Utility for reporting conflicting options #303
