### ISSUE TITLE
Implementing set built-in

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#149]
- [x] Printing existing variables (`set` without arguments)
- [x] Printing current option settings (`set -o`)
- [x] Printing current option settings (`set +o`)
- [x] Modifying option settings
- [x] Modifying positional parameters
