### ISSUE TITLE
Implementing jobs built-in (POSIX portability)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#155]
- [x] Report all jobs (without operands)
- [x] Report jobs specified by operands
- [x] Verbose format (`-l`)
- [x] Only print process group IDs (`-p`)
