### ISSUE TITLE
Implementing syntax parser (non-POSIX extensions)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#259]
- Configutation
  - [ ] Toggling non-POSIX extensions
- Redirections
  - [ ] Process redirections (`<(foo)`, `>(foo)`)
- Word units
  - Dollar units (`$...`)
    - Parameter expansion with braces (`${FOO}`)
      - [ ] Nested expansion (`${${foo}}`)
      - [ ] Index (`${foo[1]}`)
      - [ ] Substitution modifiers (`${foo/bar/baz}`, `${foo:/bar/baz}`, `${foo/#bar/baz}`, `${foo/%bar/baz}`, `${foo//bar/baz}`)
    - [ ] Character expansion (`$'\a'`)
- Compound commands
  - [ ] Double bracket constructs (`[[ ... ]]`)
- Function definitions
  - [ ] With `function` keyword
