### ISSUE TITLE
Implementing shell language semantics (non-POSIX extensions)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#260]
This is a tracking issue for implementation of the non-portable part of the shell language semantics.
For the semantics required by POSIX, see #51.

- Word expansion
    - Tilde expansion
        - [ ] `~+`
        - [ ] `~-`
        - [ ] `~+n`, `~-n`
    - Parameter expansion
        - [x] Array variable expansion abf4976 #140
        - [ ] Nested expansion
        - [ ] Index
        - Switch modifiers
            - [ ] Assignment to an array like `${a[1]:=foo}`
        - [ ] #201
    - [ ] Arithmetic expansion (non-POSIX extensions)
    - [ ] Character expansion (`$'...'`)
    - [ ] Brace expansion
- Command execution
    - Simple command
        - [ ] Command search cache (hash)
        - [ ] `COMMAND_NOT_FOUND_HANDLER`
    - Compound commands
        - [ ] Double brackets (`[[ ... ]]`)
- Redirections
    - [ ] Sockets (/dev/tcp/..., /dev/udp/...)
    - [ ] Pipe redirection (`>>|`)
    - [ ] Here-string (`<<<`)
    - [ ] Process redirections (`<(...)`, `>(...)`)
- Signal handling
    - [ ] (Run traps while reading commands)
    - [ ] Implement [missing tests](https://github.com/magicant/yash-rs/pull/114/files#diff-b9aa8606985836413fcbfcef292bb0c68be63f98629261c953f657fbcaba635fR140-R142)

### Possible optimizations

- [ ] Omit removing signal catching handlers when starting a subshell that is just `exec`ing
- [ ] The `finally_exit` flag: avoid unnecessary fork & wait if a command is known to be the last in the current shell execution environment.
