### ISSUE TITLE
Command-line argument parsing for built-ins (non-POSIX extensions)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#321]
Features needed for POSIX support are tracked in #122.

- [ ] Mode: options after operands
- [ ] Mode: enabling/disabling the `--` separator
- [ ] Mode: treating a hyphen followed by digits as an option or operand
- [ ] Mode: rejecting non-portable options
- [ ] Help (printing summary of available options)
