### ISSUE TITLE
Todos to be addressed before the first beta release

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#336]
We need to address the following issues before the first beta release, which aims to be feature-complete with respect to POSIX 2018.

- [x] Update README
- Failing scripted tests
    - alias-p.sh
        - [x] [alias substitution to empty string](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/alias-p.sh#L173)
        - [x] [alias substitution to blank before newline](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/alias-p.sh#L198)
        - [x] [line continuation between alias names (1)](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/alias-p.sh#L547)
        - [x] Maybe #280
	- command-p.sh
		- [x] [command exec retains redirection](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/command-p.sh#L42)
	- errexit-p.sh
		- [x] [errexit: last of pipeline](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/errexit-p.sh#L76) #362
    - for-p.sh
        - [x] [exit status with no words](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/for-p.sh#L139) #363
    - option-p.sh
        - [x] [nounset on: unset variable ${foo+bar}](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/option-p.sh#L289) #363
        - [x] [nounset on: unset variable ${foo:+bar}](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/option-p.sh#L296) #363
    - param-p.sh
        - [x] [length of unset variables, success](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/param-p.sh#L256) #363
    - path-p.sh
        - [x] [expansion with unsearchable directory](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/path-p.sh#L80) #364
    - quote-p.sh
        - [x] [backslashes resulting from expansions (a pattern)](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/quote-p.sh#L583) #364
    - redir-p.sh
        - [x] [here-document with non-default file descriptor](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/redir-p.sh#L318) #364
        - [x] [multiple here-documents on single command](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/redir-p.sh#L479) #364
    - trap-p.sh
        - [x] [fatal shell error in trap](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/trap-p.sh#L122) #364
        - [x] [trap command is not affected by redirections effective when set (4)](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/tests/scripted_test/trap-p.sh#L169) #364
- Yash-arith crate
    - None
- Yash-builtin crate
    - None
- Yash-cli crate
    - [x] [Disable non-blocking I/O on stdin](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash/src/lib.rs#L87) 071779f
- Yash-env crate
    - [x] [Use eaccess](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/system/real.rs#L111) 7534090
    - [x] [Elaborate catch_signal](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/system/real.rs#L132) 33562bd
    - [x] [Support real-time signals](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/trap/cond.rs#L22) [(2)](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/trap/cond.rs#L74)
        - #367
        - #368
    - [x] [Variable::expand should require mutable self](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/variable/main.rs#L144) 528c57d5c408e4e236988fed1895f15a2d8c93f1
    - [x] [Document VariableRefMut](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/variable/main.rs#L163) 468ae20ce25c7baa34402764bc02771241038e2b
    - [x] [Report invalid UTF-8 bytes rather than ignoring them](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/input.rs#L105) 7e0a45a9092add99e693a7cf10489563a489f933
    - [x] [Make Frame non-exhaustive](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/stack.rs#L57) 35167517c727ee566a99655bce88b7fa04a2ef90
    - [x] [Elaborate SelectSystem](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/system.rs#L1038) 57122ee2c2b6a012452817d687887d54bc314bc1
    - [x] [Elaborate AsyncIo](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/system.rs#L1176) 57122ee2c2b6a012452817d687887d54bc314bc1
    - [x] [Elaborate AsyncSignal](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/system.rs#L1358) 57122ee2c2b6a012452817d687887d54bc314bc1
    - [x] [Extend internal handlers for other signals](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-env/src/trap.rs#L92) fb1c3a6875f7e2e60522df76c3f6511c44f53178
- Yash-semantics crate
    - [x] [Use /proc/self/exe in fall_back_on_sh](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/command/simple_command/external.rs#L220) f75a0196c3b9cfc2748fcdae169c2fe339bc6197
    - [x] [Use pretty::Message and annotate_snippet](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/command/function_definition.rs#L65) f1e352f32966aa329f512d5e46f1074414c51da4
    - [x] [Elaborate Expand for TextUnit](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/expansion/initial/text.rs#L64) [(2)](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/expansion/initial/text.rs#L70) 88966649a00026fcf6fb4a2258545ccbdb0f8f94
    - [x] [Should we suppress return/break/continue from trap?](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/trap/signal.rs#L329) 905576f650221edfb99d4cb6461ce90d3a0489c2
    - [x] [Elaborate: Command::execute](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-semantics/src/command.rs#L37) 88966649a00026fcf6fb4a2258545ccbdb0f8f94
- Yash-syntax crate
    - [x] [Consider merging EmptyParam & UnclosedParam into InvalidParamName](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/parser/lex/braced_param.rs#L115) ccdc4a6950ce2435b82f26cec0d02847e3970ea5
        - We should possibly add InvalidCharInParam to EmptyParam & UnclosedParam.
    - [x] [Elaborate the parser::lex::tilde module](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/parser/lex/tilde.rs#L19) 68ec27368bfb145254776485916c72b661302f6b
    - [x] [Include the corresponding here-doc operator](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/parser/error.rs#L63) 34035d1db738d4105936f4f861c9c5a97a1e6998
        - Probably we don't need to do anything.
    - [x] [Most FromStr implementations ignore trailing redundant tokens, which should be rejected](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/parser/from_str.rs#L32) 93ecc26f1875fada27cc89a0222bcd12323788f7
    - [x] [Elaborate the syntax::pretty module](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/source/pretty.rs#L31) 47cb94a4565725a4990a0e95bd5b281cb0c1db24
    - [x] [Avoid printing a keyword as the first word](https://github.com/magicant/yash-rs/blob/ea225668b417c99fc661b07f1fd1d06966bcc49d/yash-syntax/src/syntax.rs#L975) 50c2c38727760d44355a4c13928a02996670ddae
