### ISSUE TITLE
Make yash-env and its dependents buildable on non-Unix platforms

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#398]
The `yash-env` crate should build on any platform. On non-Unix platforms, however, `RealSystem` is disabled.

- [x] Make `Pid` buildable on non-Unix platforms c80826f84bd250e458adc69c900da131013f7bc7
- [x] ~~Make `yash_env::system::fd_set` independent of nix and libc~~ Remove `yash_env::system::fd_set` #399
- [x] Make `yash_env::system::virtual` independent of nix and libc
- [x] Make `yash_env::system::virtual` independent of `OsStr` and `Path` #401
- [x] Conversion between `yash_env::system::Errno` and `nix::errno::Errno` is not available on non-Unix targets ca5722ccc749971b11166799c9d8f35c123f367c
