### ISSUE TITLE
Implementing shell language semantics (POSIX portability)

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#51]
This is a tracking issue for implementation of the portable part of the shell language semantics.
For yash-specific semantics, see #260.

- [x] #102
- Word expansion
    - [x] Literal character 783986c7 e1f2cbad
    - [x] Backslashes ~~c4fe703~~ 74aa07c7
    - [x] Single-quotes ~~19575fb~~ e1f2cbad
    - [x] Double-quotes ~~#74~~ 0c6c06c5
    - [x] #190
    - Parameter expansion
        - [x] Scalar variable expansion ~~#79~~ 79db2e93
        - [x] Special parameter expansion
            - [x] `?`, `!` ~~#95~~ 79db2e93
            - [x] `@`, `*` #145
            - [x] `#` d90ea112de8f8063a6619a503edef546874503de
            - [x] `-` 09439345b859caf593eb5714c28615922074ad99
            - [x] `$` ~~b96602c~~ 79db2e93
            - [x] `0` 83d54d93198e8202700f9bde267ca0250a94aefa
        - [x] Length modifier 233332461bb3223cd1289ca9eb69ab6ba4e88373
        - [x] #197
        - [x] #202
    - [x] Command substitution ~~#103~~ 6f8d1a6f
    - [x] #169
    - [x] #156
    - [x] #158
    - [x] Quote removal & attribute stripping ~~031f694~~ #142
- Command execution
    - [x] List 84b96c68eeb43e52a58ef816db7d04d89f56c650 35742dcc570360ae7753d2c3f11589a87b387bf2
    - [x] #78
    - [x] #62
    - [x] #92
    - [x] #80
    - Compound commands
        - [x] Braces (`{ foo; }`) 4b0693479390cbcf0ef732a9dd792c8ccc64e1de
        - [x] #166 (`(foo)`)
        - Loops
            - [x] #167
            - [x] #168
            - [x] #188
            - [x] #189
        - [x] #184
        - [x] If conditional construct d2d5d7ec47dfbab132e83bdfc7ee72de7446992c
        - [x] Redirections fb9d2a680ec7acc7215c6c1767f0fcab9208f5ef
    - [x] #76
- Redirections
    - [x] #87 (`<`, `>`, `>|`, `>>`, `<>`)
    - [x] #194 (`<&`, `>&`)
    - [x] #195 (`<<`, `<<-`)
- [x] #204
- [x] #109
- Properties of special built-in utilities
    - See #80 and #204

**Comment by magicant** [comment]
So, what should we start with? 🤔 

- List
    - A method to test side effects
        - (Simulated) standard output
        - The echo built-in, or a fake of it
    - A method to test exit status
        - Exit status in Env
        - A fake built-in that returns an arbitrary exit status
- More on simple command
    - Assignment
        - Variables in Env
    - Command search
        - Functions in Env
        - A (simulated) method to test whether a file is executable
    - Executing external commands
        - Creating subshells in Env
        - Performing `exec` in Env
- Basic part of word expansion
    - Type of word expansion functions
    - Variables in Env
