### ISSUE TITLE
Executing pipelines

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#62]
- [x] Opening a pipe
- [x] Duplicating an FD
- [x] Closing an FD
- [x] Put pipeline commands in Rc #66
- [x] Running subshells simultaneously (starting a subshell asynchronously) #66
- [x] Complete partially unimplemented test (`pipe_connects_commands_in_pipeline`) #70
    - Requires `select` in `cat_builtin_main`
    - SharedSystem::select should wait until the condition is met (rather than immediately returning 0). Pipes should have some condition variable to wake it up.
        - Can we make System::select async for that?
    - Calling a parent Env's select should also select in child Envs
        - Keep child SharedSystems in parent SharedSystem or in parent VirtualSystem?
        - Call select repeatedly in DummyChildProcess::run?
- [x] Handle Divert in subshell cfa98498affdb00c8a40da54272882ecfa84577c
- [x] Convert signal number to exit status for signaled child process
- [x] Handle all wait statuses 856a30dba6046c8cdfa5a1ca8a54379c996e75d7
- [x] Inverting the exit status with the `!` keyword
- Method to test I/O on pipes with VirtualSystem
    - [x] System::read
    - [x] System::write
    - [x] Virtual pipe
    - [x] Virtual open file description (pipe reader)
    - [x] Virtual open file description (pipe writer)
    - [x] Virtual open file description (file reader/writer)
    - [x] Virtual file descriptor
    - [x] Default stdin/stdout
    - [x] Dummy `cat` built-in or something alike

In the minimum implementation of pipeline execution, the shell is not required to wait for all the subshells of a pipeline. It suffices to waiting only for the last subshell, so it is out of scope of this issue to manage all the child processes of a pipeline in the environment. (Do we need to add a pid parameter to System::wait_sync so we can wait for a particular child process?)

**Comment by magicant** [comment]
Pipeline commands are run in a subshell concurrently, so the command cannot be just borrowed and passed to the subshell. Probably `Pipeline` should be redefined as:

```rust
pub struct Pipeline<H = HereDoc> {
    pub commands: Rc<Vec<Command<H>>>,
    pub negation: bool,
}
```
