### ISSUE TITLE
Executing functions

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#77]
- [x] Executing the function body e66007539a39c5903c1d0c997dbd31dcdf1aaf63
- [x] Creating and destroying a variable context #96
- [x] Setting local positional parameters from the command arguments #107
- [x] Handling `return` from inside the function #106
