### ISSUE TITLE
Executing simple command

### ISSUE THREAD

**Issue by magicant** [magicant/yash-rs#80]
- [x] Word expansion
- [x] Redirections (common part) #86
- [x] Assignments (common part) #81
- [x] #54

----

- Absent target (word expansion resulting in zero fields)
    - [x] Performing redirections in a subshell 26f19ef1d67b6d2c14a31b5a1cbb3ee37e775f8d
    - [x] Applying assignments to the current shell environment #81
    - [x] #104
- Invoking a built-in
    - [x] Applying redirections to the built-in a4ae105d86db3c9fd2af5adb1da406de70a90fb1
    - [x] Applying assignments to the current shell environment (special built-in only) e127ccfc38fca89af3db0204b77c6e7eeccc9322
    - [x] Exporting assignments in a temporary context (regular built-in only) 3bc72b595436eefc18a7d4ff41db0bed5c14578d
    - [x] Invoking the built-in body
- Invoking a function
    - [x] Applying redirections to the function d46dd724c044d0a531ee3a1535d4ba825a0a6178
    - [x] Exporting assignments in a temporary context #97 #99
    - [x] #77
- Invoking an external utility
    - [x] Applying redirections to the utility #86
    - [x] Exporting assignments to the utility d8fe8f73edd948936f199b95c362d9631f924027
    - [x] #59
- Target not found
    - [x] Performing the same action as invoking an external utility (*) 4fc393c94b6ca72d1d2f7b48f9c5aaca24399154
- Handling errors (error message and exit status)
    - [x] Target not found 4fc393c94b6ca72d1d2f7b48f9c5aaca24399154
    - [x] Expansion errors b53688859e20edcfb97366ad21b00ac1b1492060 feb591ba05c833b5541f344e57dbccebebe3c5be
    - [x] Redirection errors #86
    - [x] Assignment errors #81

(*) If the command name contains a slash, the command search is skipped, so the shell has no idea whether the command name actually names an existing executable file. That means redirections and assignments are performed even though the external utility invocation is going to fail later. The behavior for command names not containing a slash should be consistent with that.

----

Bugs:

- [x] #100

**Comment by magicant** [comment]
Road map for implementing redirection

- `<` redirection for external utility in simple command
    - Expanding the operand and opening a file
- Applying redirections to built-ins
    - Temporary redirection context / unwinding of redirection
- Applying redirections to functions
- `>` and other kinds of redirections

----

What if redirection is overwritten while executing a function or built-in?

```sh
exec 3<file1
f() { exec 3<file2; }
f 3<file3
cat <&3
# Many existing shells (bash, dash, ksh, mksh, zsh, and yash) print "file1"
```

```sh
exec 3<file1
eval 'exec 3<file2' 3<file3
cat <&3
# Many existing shells (bash, dash, ksh, mksh, zsh, and yash) print "file1"
```
